#!/usr/bin/env bash
#
# Fuzzy find a project folder, creates a new Tmux session, and attaches to it.

set -ou pipefail

export FZF_DEFAULT_OPTS='
     --height 100%
     --layout=reverse
     --inline-info
     --color=fg:#e5e9f0,hl:#81a1c1
     --color=fg+:#e5e9f0,bg+:#3b4252,hl+:#81a1c1
     --color=info:#eacb8a,prompt:#bf6069,pointer:#b48dac
     --color=marker:#a3be8b,spinner:#b48dac,header:#a3be8b'
PROJECTS_DIRS="$(cat ~/.config/tmux/projects_dirs)"

project_folder=$(fd . --type d $PROJECTS_DIRS --max-depth 1 | fzf)
session_name=$(echo "$project_folder" | awk -F "/" '{print $NF}')

if ! tmux has-session -t "$session_name" 2>/dev/null; then
	tmux new-session -d -s "$session_name" -c "$project_folder"
fi

if [[ $session_name == "" ]]; then
  exit 0;
fi

tmux switch-client -t "$session_name"
