return {
  'nvim-treesitter/nvim-treesitter',
  dependencies = {
    'nvim-treesitter/playground',
  },
  branch = 'master',
  lazy = false,
  build = ':TSUpdate',
  config = function()
    require("nvim-treesitter.configs").setup({
      ensure_installed = {
        "asm",
        "bash",
        "c",
        "cpp",
        "css",
        "csv",
        "csv",
        "dockerfile",
        "dot",
        "editorconfig",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gpg",
        "html",
        "javascript",
        "jq",
        "json",
        "just",
        "latex",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "nginx",
        "python",
        "query",
        "r",
        "regex",
        "rst",
        "ruby",
        "rust",
        "sql",
        "ssh_config",
        "terraform",
        "tlaplus",
        "tmux",
        "toml",
        "typescript",
        "typst",
        "vim",
        "vimdoc",
        "yaml",
        "zig",
      },
      sync_install = true,
      highlight = { enable = true },
      indent = { enable = true },
    })
  end
}
