#!/usr/bin/env bash

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

###############################################################################
###                              TILING                                     ###
###############################################################################
yabai -m config external_bar                 off:45:0
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
# BUG: enable it after fix
# The border feature stope working on Monterey
# yabai -m config window_border                on
# yabai -m config window_border_width          6
# yabai -m config active_window_border_color   0xff5E81AC
# yabai -m config normal_window_border_color   0xff8FBCBB
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

###############################################################################
###                             LAYOUT                                      ###
###############################################################################
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15

###############################################################################
###                              ERGONOMICS                                 ###
###############################################################################
yabai -m space 1 --label misc 
yabai -m space 2 --label code
yabai -m space 3 --label personal 
yabai -m space 4 --label work
yabai -m space 5 --label chat 

source $HOME/.config/yabai/local

echo "yabai configuration loaded ..."
