#!/usr/bin/env bash
###############################################################################
# .nbrc
#
# Configuration file for `nb`, a command line note-taking, bookmarking,
# and knowledge base application with encryption, search, Git-backed syncing,
# and more in a single portable script.
#
# Edit this file manually or manage settings using the `nb settings`
# subcommand. Configuration options are set as environment variables, eg:
#   export NB_ENCRYPTION_TOOL=gpg
#
# https://github.com/xwmx/nb
###############################################################################
nb_dir="$(cat ~/.dropbox/info.json | jq -r '.business.path')/anmerkungen/"
export EDITOR="nvim"
export NB_COLOR_THEME="smoke"
export NB_DIR=$nb_dir
export NB_SYNTAX_THEME="Nord"
